# Copyright (C) 2026 Simson L. Garfinkel. All Rights Reserved.

"""Copyright requirement: preserve third-party/generated bytes and cover new source forms."""

from pathlib import Path
import shlex
import shutil
import subprocess
import sys

import pytest

from scripts.check_copyright import NOTICE, expected_header, is_eligible


@pytest.mark.parametrize("filename", [
    "website/static/images/hands-typing.svg", "gui/vendor/tabulator/tabulator.min.js",
    "website/themes/envelope-rainbow/templates/index.html", "tests/data/message.eml",
    "uv.lock", ".agents/skills/pr-to-ready/SKILL.md", ".claude/skills/pr-to-ready/SKILL.md",
    "CLAUDE.md", ".github/copilot-instructions.md",
])
def test_external_and_generated_material_is_not_claimed(filename: str) -> None:
    """New upstream artwork and generated workflows must not acquire project ownership notices."""
    assert not is_eligible(Path(filename))


@pytest.mark.parametrize("filename,comment", [
    ("typings/AppKit/__init__.pyi", f"# {NOTICE}"),
    ("gui/file-drag.mjs", f"/* {NOTICE} */"),
    ("src/mailarchiver/file_drag.py", f"# {NOTICE}"),
])
def test_new_source_formats_use_native_comments(filename: str, comment: str) -> None:
    """Current-main JavaScript modules and type stubs follow the same source notice policy."""
    path = Path(filename)
    assert is_eligible(path)
    assert expected_header(path) == comment


@pytest.mark.parametrize("has_notice", [False, True])
def test_copyright_findings_do_not_stop_make(tmp_path: Path, has_notice: bool) -> None:
    """Requirement: missing notices warn while dependent CI/build targets still run."""
    subprocess.run(["git", "init", "--quiet", str(tmp_path)], check=True)
    scripts = tmp_path / "scripts"
    scripts.mkdir()
    shutil.copyfile(Path(__file__).resolve().parents[1] / "scripts/check_copyright.py", scripts / "check_copyright.py")
    (tmp_path / "source.py").write_text(f"# {NOTICE}\n" if has_notice else "pass\n", encoding="utf-8")
    (tmp_path / "Makefile").write_text(
        f"# {NOTICE}\n"
        "copyright-check:\n"
        f"\t{shlex.quote(sys.executable)} scripts/check_copyright.py\n"
        "pipeline: copyright-check\n"
        "\t@echo Pipeline continued\n",
        encoding="utf-8",
    )
    result = subprocess.run(["make", "pipeline"], cwd=tmp_path, capture_output=True, text=True, check=False)
    assert result.returncode == 0, result.stdout + result.stderr
    assert "Pipeline continued" in result.stdout
    if has_notice:
        assert "WARNING" not in result.stdout
        assert "Copyright notice present in 3 eligible files." in result.stdout
    else:
        assert "WARNING: Missing the project copyright notice:" in result.stdout
        assert "source.py" in result.stdout
