# Copyright (C) 2026 Simson L. Garfinkel. All Rights Reserved.

"""Objective-C dispatch used by the native quit and file-drag adapters."""
from typing import Any, Protocol
from collections.abc import Callable
from AppKit import Point

class _NativeSuperclass(Protocol):
    def applicationShouldTerminate_(self, app: object) -> int: ...
    def dragImage_at_offset_event_pasteboard_source_slideBack_(self, image: object, point: Point, offset: Point, event: object, pasteboard: object, source: object, slide_back: bool) -> None: ...
    def beginDraggingSessionWithItems_event_source_(self, items: list[object], event: object, source: object) -> Any: ...

def super(cls: type, instance: object) -> _NativeSuperclass: ...

def classAddMethods(cls: type, methods: list[Callable[..., object]]) -> None: ...
