# Copyright (C) 2026 Simson L. Garfinkel. All Rights Reserved.

"""Minimal AppKit selectors used by mailarchiver; no runtime replacement."""
from typing import Any, Self
from collections.abc import Mapping
from Foundation import NSURL as NSURL

type Point = tuple[float, float]
type Rect = tuple[Point, Point]

NSPasteboardTypeString: str
NSPasteboardTypeFileURL: str
NSPasteboardTypeURL: str
NSFilenamesPboardType: str

class NSPasteboard:
    @classmethod
    def generalPasteboard(cls) -> Self: ...
    @classmethod
    def pasteboardWithUniqueName(cls) -> Self: ...
    def releaseGlobally(self) -> None: ...
    def types(self) -> list[str]: ...
    def stringForType_(self, kind: str) -> str | None: ...
    def writeObjects_(self, objects: list[object]) -> bool: ...
    def readObjectsForClasses_options_(self, classes: list[type], options: None) -> list[Any]: ...
    def clearContents(self) -> int: ...
    def setString_forType_(self, value: str, kind: str) -> bool: ...
    def setPropertyList_forType_(self, value: list[str], kind: str) -> bool: ...

class NSWorkspace:
    @classmethod
    def sharedWorkspace(cls) -> Self: ...
    def openURL_(self, url: NSURL) -> bool: ...
    def iconForFile_(self, path: str) -> NSImage: ...

class NSImage:
    @classmethod
    def alloc(cls) -> Self: ...
    def initWithContentsOfFile_(self, path: str) -> Self | None: ...
    @classmethod
    def imageWithSystemSymbolName_accessibilityDescription_(cls, name: str, description: str) -> Self | None: ...

class NSApplication:
    @classmethod
    def sharedApplication(cls) -> Self: ...
    # Cocoa id return values depend on the installed native delegate and window.
    def mainMenu(self) -> Any: ...
    def delegate(self) -> Any: ...
    def modalWindow(self) -> Any: ...
    def sendAction_to_from_(self, action: object, target: object, sender: object) -> bool: ...
    def stopModalWithCode_(self, code: int) -> None: ...
    def setMainMenu_(self, menu: object) -> None: ...
    def setApplicationIconImage_(self, image: NSImage) -> None: ...


NSTerminateCancel: int

class NSAlert:
    @classmethod
    def alloc(cls) -> Self: ...
    def init(self) -> Self: ...
    def setMessageText_(self, text: str) -> None: ...
    def setInformativeText_(self, text: str) -> None: ...
    def addButtonWithTitle_(self, title: str) -> NSButton: ...
    def setIcon_(self, icon: NSImage | None) -> None: ...
    def setAccessoryView_(self, view: object) -> None: ...
    def window(self) -> Any: ...
    def runModal(self) -> int: ...


NSTerminateLater: int
NSModalPanelRunLoopMode: str
NSDeviceRGBColorSpace: str
NSTextAlignmentCenter: int
NSFontAttributeName: str
NSForegroundColorAttributeName: str
NSParagraphStyleAttributeName: str

class NSButton:
    def setKeyEquivalent_(self, value: str) -> None: ...

class NSView:
    @property
    def pyobjc_instanceMethods(self) -> Any: ...
    @classmethod
    def alloc(cls) -> Self: ...
    def initWithFrame_(self, frame: Rect) -> Self: ...
    def addSubview_(self, view: object) -> None: ...

class NSTextField:
    @classmethod
    def labelWithString_(cls, text: str) -> Self: ...
    @classmethod
    def wrappingLabelWithString_(cls, text: str) -> Self: ...
    def setSelectable_(self, value: bool) -> None: ...
    def cell(self) -> Any: ...
    def setFrame_(self, frame: Rect) -> None: ...
    def setTextColor_(self, color: NSColor) -> None: ...

class NSTextView:
    def setIdentifier_(self, value: str) -> None: ...
    def identifier(self) -> str: ...
    @classmethod
    def alloc(cls) -> Self: ...
    def initWithFrame_(self, frame: Rect) -> Self: ...
    def setRichText_(self, value: bool) -> None: ...
    def setAutomaticQuoteSubstitutionEnabled_(self, value: bool) -> None: ...
    def setAutomaticDashSubstitutionEnabled_(self, value: bool) -> None: ...
    def string(self) -> str: ...
    def setString_(self, text: str) -> None: ...
    def isEditable(self) -> bool: ...

class NSScrollView:
    @classmethod
    def alloc(cls) -> Self: ...
    def initWithFrame_(self, frame: Rect) -> Self: ...
    def setHasVerticalScroller_(self, value: bool) -> None: ...
    def setDocumentView_(self, view: object) -> None: ...

class NSOpenPanel:
    @classmethod
    def openPanel(cls) -> Self: ...
    def setTitle_(self, text: str) -> None: ...
    def setMessage_(self, text: str) -> None: ...
    def setPrompt_(self, text: str) -> None: ...
    def setAccessoryView_(self, view: object) -> None: ...
    def setCanChooseDirectories_(self, value: bool) -> None: ...
    def setCanChooseFiles_(self, value: bool) -> None: ...
    def setTreatsFilePackagesAsDirectories_(self, value: bool) -> None: ...
    def setAllowsMultipleSelection_(self, value: bool) -> None: ...
    def setCanCreateDirectories_(self, value: bool) -> None: ...
    def setDirectoryURL_(self, url: NSURL) -> None: ...
    def URLs(self) -> list[NSURL]: ...
    def runModal(self) -> int: ...

class NSColor:
    @classmethod
    def colorWithSRGBRed_green_blue_alpha_(cls, red: float, green: float, blue: float, alpha: float) -> Self: ...
    @classmethod
    def systemRedColor(cls) -> Self: ...
    def setFill(self) -> None: ...
    def redComponent(self) -> float: ...

class NSBitmapImageRep:
    @classmethod
    def alloc(cls) -> Self: ...
    def initWithBitmapDataPlanes_pixelsWide_pixelsHigh_bitsPerSample_samplesPerPixel_hasAlpha_isPlanar_colorSpaceName_bytesPerRow_bitsPerPixel_(self, planes: None, width: int, height: int, bits: int, samples: int, alpha: bool, planar: bool, color: str, row: int, pixel: int) -> Self: ...
    def setSize_(self, size: Point) -> None: ...
    def TIFFRepresentation(self) -> bytes: ...
    @classmethod
    def imageRepWithContentsOfFile_(cls, path: str) -> Self | None: ...
    def size(self) -> Point: ...
    def pixelsWide(self) -> int: ...
    def pixelsHigh(self) -> int: ...
    def colorAtX_y_(self, x: int, y: int) -> NSColor: ...

class NSGraphicsContext:
    @classmethod
    def saveGraphicsState(cls) -> None: ...
    @classmethod
    def restoreGraphicsState(cls) -> None: ...
    @classmethod
    def setCurrentContext_(cls, context: Self) -> None: ...
    @classmethod
    def graphicsContextWithBitmapImageRep_(cls, bitmap: NSBitmapImageRep) -> Self: ...

class NSMutableParagraphStyle:
    @classmethod
    def alloc(cls) -> Self: ...
    def init(self) -> Self: ...
    def setAlignment_(self, alignment: int) -> None: ...

class NSFont:
    @classmethod
    def boldSystemFontOfSize_(cls, size: float) -> Self: ...
    @classmethod
    def systemFontOfSize_(cls, size: float) -> Self: ...

class NSString:
    @classmethod
    def stringWithString_(cls, text: str) -> Self: ...
    def drawInRect_withAttributes_(self, frame: Rect, attributes: Mapping[str, object]) -> None: ...

class NSBezierPath:
    @classmethod
    def bezierPath(cls) -> Self: ...
    def moveToPoint_(self, point: Point) -> None: ...
    def lineToPoint_(self, point: Point) -> None: ...
    def closePath(self) -> None: ...
    def fill(self) -> None: ...

def NSRectFill(rect: Rect) -> None: ...


NSEventModifierFlagOption: int
NSEventModifierFlagShift: int
NSEventTypeApplicationDefined: int

class NSEvent:
    @classmethod
    def modifierFlags(cls) -> int: ...
    @classmethod
    def otherEventWithType_location_modifierFlags_timestamp_windowNumber_context_subtype_data1_data2_(
        cls, event_type: int, location: Point, modifier_flags: int, timestamp: float,
        window_number: int, context: object | None, subtype: int, data1: int, data2: int,
    ) -> Self: ...

class NSPasteboardItem:
    @classmethod
    def alloc(cls) -> Self: ...
    def init(self) -> Self: ...
    def types(self) -> list[str]: ...
    def setString_forType_(self, value: str, kind: str) -> bool: ...
    def stringForType_(self, kind: str) -> str | None: ...

class NSDraggingItem:
    @classmethod
    def alloc(cls) -> Self: ...
    def initWithPasteboardWriter_(self, writer: object) -> Self: ...
    def item(self) -> Any: ...
    def draggingFrame(self) -> Rect: ...
    def setDraggingFrame_contents_(self, frame: Rect, contents: NSImage | None) -> None: ...
